import io
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors


# ── Styles ────────────────────────────────────────────────────────────────────
def _build_styles():
    title_style = ParagraphStyle(
        "Title",
        fontSize=22,
        textColor=colors.HexColor("#0F1923"),
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        spaceAfter=4,
        leading=28,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        fontSize=11,
        textColor=colors.HexColor("#555555"),
        fontName="Helvetica",
        alignment=TA_CENTER,
        spaceAfter=20,
    )
    section_style = ParagraphStyle(
        "Section",
        fontSize=13,
        textColor=colors.HexColor("#0055AA"),
        fontName="Helvetica-Bold",
        spaceBefore=16,
        spaceAfter=8,
        borderPad=4,
    )
    body_style = ParagraphStyle(
        "Body",
        fontSize=10,
        textColor=colors.HexColor("#222222"),
        fontName="Helvetica",
        leading=16,
        spaceAfter=5,
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        fontSize=10,
        textColor=colors.HexColor("#222222"),
        fontName="Helvetica",
        leading=16,
        spaceAfter=4,
        leftIndent=12,
    )
    return title_style, subtitle_style, section_style, body_style, bullet_style


# ── Main Generator ─────────────────────────────────────────────────────────────
def generate_pdf(data: dict) -> io.BytesIO:
    """
    Generates a professional PDF research report from analysis data.

    Args:
        data (dict): Analysis result containing company info, sentiment,
                     market data, news headlines, and report text.

    Returns:
        io.BytesIO: PDF file buffer ready for download or saving.

    Expected keys in data:
        - company (str)
        - ticker (str)
        - sentiment_score (float)
        - sentiment_label (str)
        - positive_pct (int)
        - neutral_pct (int)
        - negative_pct (int)
        - news_headlines (list of str)
        - stock_price (float)
        - stock_change (str)
        - market_cap (str)
        - pe_ratio (float)
        - week_high (float)
        - week_low (float)
        - report_text (str)
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=50,
        rightMargin=50,
        topMargin=50,
        bottomMargin=50,
    )

    title_s, sub_s, sec_s, body_s, bullet_s = _build_styles()

    story = []

    # ── Header ────────────────────────────────────────────────────────────────
    story.append(Paragraph(f"Research Report: {data.get('company', 'N/A')}", title_s))
    story.append(Paragraph(
        f"Ticker: {data.get('ticker', 'N/A')}  |  Generated by FinResearch AI  |  Powered by LangGraph",
        sub_s
    ))
    story.append(Spacer(1, 6))

    # ── Divider line ──────────────────────────────────────────────────────────
    story.append(Table(
        [[""]],
        colWidths=[495],
        style=TableStyle([
            ("LINEBELOW", (0, 0), (-1, -1), 1.5, colors.HexColor("#0055AA")),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ])
    ))
    story.append(Spacer(1, 12))

    # ── Sentiment Analysis ────────────────────────────────────────────────────
    story.append(Paragraph("Sentiment Analysis", sec_s))

    sentiment_score = data.get("sentiment_score", 0)
    sentiment_label = data.get("sentiment_label", "N/A")
    positive_pct    = data.get("positive_pct", 0)
    neutral_pct     = data.get("neutral_pct", 0)
    negative_pct    = data.get("negative_pct", 0)

    story.append(Paragraph(
        f"Overall Score: <b>{sentiment_score:.2f}</b>  |  "
        f"Label: <b>{sentiment_label}</b>",
        body_s
    ))
    story.append(Paragraph(
        f"Positive: <b>{positive_pct}%</b>  |  "
        f"Neutral: <b>{neutral_pct}%</b>  |  "
        f"Negative: <b>{negative_pct}%</b>",
        body_s
    ))
    story.append(Spacer(1, 6))

    # ── Market Data ───────────────────────────────────────────────────────────
    story.append(Paragraph("Market Data", sec_s))

    market_rows = [
        ["Stock Price", f"${data.get('stock_price', 'N/A')}",
         "Change",      data.get("stock_change", "N/A")],
        ["Market Cap",  f"${data.get('market_cap', 'N/A')}",
         "P/E Ratio",   str(data.get("pe_ratio", "N/A"))],
        ["52W High",    f"${data.get('week_high', 'N/A')}",
         "52W Low",     f"${data.get('week_low', 'N/A')}"],
    ]

    market_table = Table(market_rows, colWidths=[90, 130, 90, 130])
    market_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, -1), colors.HexColor("#EEF4FF")),
        ("BACKGROUND",    (2, 0), (2, -1), colors.HexColor("#EEF4FF")),
        ("TEXTCOLOR",     (0, 0), (0, -1), colors.HexColor("#0055AA")),
        ("TEXTCOLOR",     (2, 0), (2, -1), colors.HexColor("#0055AA")),
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",      (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTNAME",      (1, 0), (1, -1), "Helvetica"),
        ("FONTNAME",      (3, 0), (3, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#CCDDEE")),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1),
         [colors.HexColor("#F7FAFF"), colors.HexColor("#FFFFFF")]),
    ]))
    story.append(market_table)
    story.append(Spacer(1, 10))

    # ── News Headlines ────────────────────────────────────────────────────────
    story.append(Paragraph("Recent News Headlines", sec_s))
    headlines = data.get("news_headlines", [])
    if headlines:
        for i, headline in enumerate(headlines, 1):
            story.append(Paragraph(f"{i}.  {headline}", bullet_s))
    else:
        story.append(Paragraph("No headlines available.", body_s))
    story.append(Spacer(1, 6))

    # ── AI Analysis ───────────────────────────────────────────────────────────
    story.append(Paragraph("AI-Generated Analysis", sec_s))
    story.append(Paragraph(data.get("report_text", "No analysis available."), body_s))
    story.append(Spacer(1, 16))

    # ── Footer line ───────────────────────────────────────────────────────────
    story.append(Table(
        [[""]],
        colWidths=[495],
        style=TableStyle([
            ("LINEABOVE", (0, 0), (-1, -1), 0.8, colors.HexColor("#CCCCCC")),
            ("TOPPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ])
    ))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by FinResearch AI  |  For educational purposes only  |  Not financial advice",
        ParagraphStyle("Footer", fontSize=8, textColor=colors.HexColor("#999999"),
                       fontName="Helvetica", alignment=TA_CENTER)
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer


# ── Save to file (used by backend) ────────────────────────────────────────────
def save_pdf(data: dict, filepath: str) -> str:
    """
    Generates PDF and saves it to a file path.
    Used by the FastAPI backend when saving reports server-side.

    Args:
        data (dict): Same data dict as generate_pdf()
        filepath (str): Where to save the PDF e.g. 'reports/Apple_report.pdf'

    Returns:
        str: The filepath where PDF was saved
    """
    import os
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    buffer = generate_pdf(data)
    with open(filepath, "wb") as f:
        f.write(buffer.read())
    print(f"[PDFGenerator] Saved report to {filepath}")
    return filepath


# ── Quick test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    sample_data = {
        "company":         "Apple",
        "ticker":          "AAPL",
        "sentiment_score": 0.72,
        "sentiment_label": "Positive",
        "positive_pct":    72,
        "neutral_pct":     21,
        "negative_pct":    7,
        "news_headlines": [
            "Apple hits record quarterly revenue of $120B",
            "iPhone 16 sales surpass analyst expectations",
            "Apple expands AI features across product lineup",
            "Apple stock reaches all-time high amid strong earnings",
            "New MacBook with M4 chip receives rave reviews",
        ],
        "stock_price":  189.50,
        "stock_change": "+1.2%",
        "market_cap":   "2.94T",
        "pe_ratio":     28.5,
        "week_high":    198.23,
        "week_low":     142.10,
        "report_text": (
            "Apple Inc. demonstrated strong positive momentum this week, driven by "
            "better-than-expected quarterly earnings and continued growth in its services "
            "segment. Sentiment across financial media remained largely bullish, with analysts "
            "highlighting the company's expanding AI integration as a key growth driver."
        ),
    }

    # Test 1 — generate buffer (used by Streamlit download button)
    pdf_buffer = generate_pdf(sample_data)
    print(f"PDF buffer generated: {pdf_buffer.getbuffer().nbytes} bytes")

    # Test 2 — save to file (used by FastAPI backend)
    save_pdf(sample_data, "test_output/Apple_report.pdf")
    print("Both tests passed!")